### ISSUE TITLE
Unmasking the hash function G for key generation and encapsulation processes.

### ISSUE THREAD

**Issue by aadomn** [uclcrypto/pqm4_masked#1]
Hello,

I was playing with your code when I realized that performance of the key generation and encapsulation processes were varying depending on the `NSHARES` parameter.
It seems to be due to the fact that the hash function G (SHA3-512) relies on a masked implementation:
`#define hash_g(OUT, IN, INBYTES) sha3_512_masked_check(OUT, IN, INBYTES)` in `symmetric.h`.
It seems to me that using a non-masked SHA3-512 implementation:
`#define hash_g(OUT, IN, INBYTES) sha3_512(OUT, IN, INBYTES)`
would not affect the security of the masking scheme for the decapsulation while preserving the performance for the key generation and encapsulation process, right?
Since you directly call `masked_sha3_512` in `crypto_kem_dec`, it should not cause any issue in your code.

Thanks in advance for your feedback.

Cheers,
Alexandre Adomnicai

**Comment by obronchain** [comment]
Hi Alexandre, 

You are totally correct, this is a bug. We focused on the performances of the decap,  probably explaining why we have not spotted it before. 

This only affects the Kyber and not Saber. 

I'll fix the code and run all the proper test routines once I am back in the lab (and have the boards).

Thanks again, 

Olivier

**Comment by cassiersg** [comment]
This has been fixed in fed1788
