### ISSUE TITLE
Issues with the global benchmarking scripts

### ISSUE THREAD

**Issue by rben-dev** [uclcrypto/pqm4_masked#2]
Hi,

First of all, thanks for this work and for sharing it!

Regarding the benchmarks and the `parse_bench.py` script, there are two issues:
- The name of the file in the repository is misspelled: `pars_bench.py`.
- The `run_bench.sh` script generates the files `target_{c|asm}_cycles.csv` where `target` is either `kyber768` or `saber`. The check in the `pars_bench.py` to detect the files fails because of the `{c|asm}` addition: it could be e.g. replaced with the more lax `if "kyber768" in target:`.
- More importantly, this script seeks for the random csv file `target_rnd.csv` which does not seem to be produced by the `sh` script (or am I missing something?), making the whole plotting script fail.

Thanks in advance,
Regards,

**Comment by cassiersg** [comment]
cc @cmomin

**Comment by cassiersg** [comment]
Thanks for reporting the issue!
